force-app/main/default/objects/Order_Event__e/Order_Event__e.object-meta.xml
<CustomObject>
    <label>Order Event</label>
    <pluralLabel>Order Events</pluralLabel>
    <description>Information about a customer order</description>
</CustomObject>

force-app/main/default/objects/Order_Event__e/fields/Has_Shipped__c.field-meta.xml
<CustomField>
    <fullName>Has_Shipped__c</fullName>
    <label>Has Shipped</label>
    <type>Checkbox</type>
    <defaultValue>false</defaultValue>
</CustomField>

force-app/main/default/objects/Order_Event__e/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <type>Text</type>
    <length>10</length>
</CustomField>

force-app/main/default/classes/OrderEventPublisher.cls
public class OrderEventPublisher {
    public static void publish(String orderNumber, Boolean hasShipped) {
        Order_Event__e event = new Order_Event__e(
            Order_Number__c = orderNumber,
            Has_Shipped__c = hasShipped
        );

        Database.SaveResult sr = EventBus.publish(event);

        if (sr.isSuccess()) {
            System.debug('Successfully published Order Event.');
        } else {
            for (Database.Error err : sr.getErrors()) {
                System.debug('Error: ' + err.getStatusCode() + ' - ' + err.getMessage());
            }
        }
    }
}